include:
  - board: xiao_ble//zmk
    shield: kod_04_left
    cmake-args: -DZMK_EXTRA_MODULES=${GITHUB_WORKSPACE}/modules/led_status
  - board: xiao_ble//zmk
    shield: kod_04_right
    cmake-args: -DZMK_EXTRA_MODULES=${GITHUB_WORKSPACE}/modules/led_status
