# 右手専用：トラックポイント設定

# ポインティングデバイス
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_INPUT_PS2=y

# ログ（デバッグ用）
CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_INPUT_LOG_LEVEL_DBG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_LOG_DEFAULT_LEVEL=4
