# --------------------------------
# kod_04.conf
# 共通設定
# --------------------------------

# ZMK基本設定
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_SPLIT=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=2

# BLE接続数
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=2

# ロータリーエンコーダー（左手）
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_KEYMAP_SENSORS=y

# マウス機能（必須）⭐⭐⭐
CONFIG_ZMK_POINTING=y

# 省電力設定
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Split BLE の遅延軽減
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

# Split BLE キューを拡大
CONFIG_ZMK_SPLIT_BLE_CENTRAL_POSITION_QUEUE_SIZE=20
CONFIG_ZMK_SPLIT_BLE_PERIPHERAL_POSITION_QUEUE_SIZE=20
CONFIG_ZMK_LED_STATUS=y
