# --------------------------------
# kod_04_right.conf
# 右側 = central + PS/2 TrackPoint
# --------------------------------

# 右側もログはオフ
CONFIG_LOG=n

# Pointing / Input
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y

# PS/2 を少し優先
CONFIG_PS2_INIT_PRIORITY=1

# エラーミティゲーションは切る
# （今は input_mouse_ps2.c 側で個別に drop 条件を入れているため）
CONFIG_ZMK_INPUT_MOUSE_PS2_ENABLE_ERROR_MITIGATION=n
