manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: yourgithub
      url-base: https://github.com/kodomari

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: yourgithub
      revision: fix--zephyr41
      path: modules/kb_zmk_ps2_mouse_trackpoint_driver

  self:
    path: config
