name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-west-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-west-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: Build left
        run: west build -s zmk/app -b xiao_ble -- -DSHIELD=kod_04_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename left artifact
        run: cp build/zephyr/zmk.uf2 kod_04_left-xiao_ble-zmk.uf2

      - name: Build right
        run: |
          rm -rf build
          west build -s zmk/app -b xiao_ble -- -DSHIELD=kod_04_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename right artifact
        run: cp build/zephyr/zmk.uf2 kod_04_right-xiao_ble-zmk.uf2

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            kod_04_left-xiao_ble-zmk.uf2
            kod_04_right-xiao_ble-zmk.uf2
